node .\node_modules\reffy\src\cli\parse-webidl.js "https://immersive-web.github.io/webxr/" > IDL\WebXRDeviceAPI.json
node .\node_modules\reffy\src\cli\parse-webidl.js "https://immersive-web.github.io/webxr-gamepads-module/" > IDL\WebXRGamepadsModule.json
node .\node_modules\reffy\src\cli\parse-webidl.js "https://immersive-web.github.io/webxr-ar-module/" > IDL\WebXRAugmentedRealityModule.json
node .\node_modules\reffy\src\cli\parse-webidl.js "https://immersive-web.github.io/hit-test/" > IDL\WebXRHitTestModule.json
node .\node_modules\reffy\src\cli\parse-webidl.js "https://immersive-web.github.io/dom-overlays/" > IDL\WebXRDOMOverlaysModule.json
node .\node_modules\reffy\src\cli\parse-webidl.js "https://immersive-web.github.io/layers/" > IDL\WebXRLayersAPILevel1.json
node .\node_modules\reffy\src\cli\parse-webidl.js "https://immersive-web.github.io/anchors/" > IDL\WebXRAnchorsModule.json
node .\node_modules\reffy\src\cli\parse-webidl.js "https://immersive-web.github.io/lighting-estimation/" > IDL\WebXRLightingEstimationAPILevel1.json
node .\node_modules\reffy\src\cli\parse-webidl.js "https://immersive-web.github.io/webxr-hand-input/" > IDL\WebXRHandInputModuleLevel1.json